baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[permalinks]
  productos = "/productos/:filename/"

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Pagina 1"
  url = "/pag1/"
  weight = 2

[[menu.main]]
  name = "Pagina 2"
  url = "/pag2/"
  weight = 3
