baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  css=["css/styles.css"]

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Pagina 1"
  url = "/pag1/"
  weight = 2

[[menu.main]]
  name = "Pagina 2"
  url = "/pag2/"
  weight = 3

[[menu.main]]
  name = "Pagina 3"
  url = "/pag3/"
  weight = 4

[[menu.main]]
  name = "Pagina 4"
  url = "/pag4/"
  weight = 5



